name: Build Illusion Kernel 5.4 for Beryllium

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_clang_host_linux-x86_clang-r450784e clang
          echo "CLANG_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV

      - name: Setup Environment Variables
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-android-" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "KBUILD_COMPILER_STRING=$(${{ env.CLANG_PATH }}/bin/clang --version | head -n 1)" >> $GITHUB_ENV

      - name: Build Kernel
        run: |
          make O=out beryllium_defconfig
          make -j$(nproc) O=out \
            CC=${{ env.CLANG_PATH }}/bin/clang \
            CROSS_COMPILE=${{ env.CLANG_PATH }}/bin/${{ env.CROSS_COMPILE }} \
            CLANG_TRIPLE=${{ env.CLANG_PATH }}/bin/${{ env.CLANG_TRIPLE }}

      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v3
        with:
          name: Kernel-Image
          path: out/arch/arm64/boot/Image.gz-dtb


---
